// Counting Variable
var iter = -1;

places = []; placePage = [];

iter+=1;
places[iter] = {name:"Grindr Stadium", siteLink:"grindr-stadium",shortDescription:"A premier indoor arena hosting concerts, sports, and the annual Golden City Awards.",coverImg:"https://reuvenrey.github.io/visitds/files/images/placeholder.jpg",categories:[3], location:3, coordinates:"TBD", completeness:0};
placePage[iter] = {tags:["Sports","Concert Venue","Indoor","Hockey","Golden City Awards"], dateEstablished:"May 1, 2025", longDescription:"This is the worlds greatest Arena, it really is! It's truly the best"};

iter+=1;
places[iter] = {name:"The Torchlight Theater", siteLink:"torchlight-theater",shortDescription:"A historic theater and cornerstone of the Desert Springs arts movement",coverImg:"https://i.imgur.com/XPbbuGz.png",categories:[3,8], location:3, coordinates:"", completeness:2};
placePage[iter] = {tags:["Historic","The Alley"], dateEstablished:"1960", longDescription:"Long before the massive 2,000-seat theaters you see today along West Ave, this humble 200-seat theater entertained some of Desert Springs original city residents. Today, it's home to comedy shows, school performances, local plays, and more. The Torchlight is a testament to the long history of arts and culture in the city.<br><br>Though the technology within has been upgraded, much of the theater's original furnishings and exterior remain, thanks to a restoration project funded by the Lea Kra Sasson Civic Arts Fund (LKSCA).", slideshowLinks:["https://i.imgur.com/57VRjdZ.png","https://i.imgur.com/F40wAu7.png","https://i.imgur.com/QEBkrEK.png","https://i.imgur.com/oLGZaiv.png"]};

iter+=1;
places[iter] = {name:"Infinity Casino & Resort", siteLink:"infinity-casino-resort",shortDescription:"A luxurious high-rise Casino & Hotel featuring the world's largest BJ's Restaurant and Brewhouse",coverImg:"https://i.imgur.com/G9B01BQ.png",categories:[0,1,2], location:3, coordinates:"", completeness:2};
placePage[iter] = {tags:["Rooftop Pool","Pizookie","Hotel","Gambler's Club","Brewery"], dateEstablished:"", longDescription:"A dazzling fusion of excitement and elegance, the Infinity Casino & Resort delivers nonstop gaming, world-class luxurious accommodations, and the world’s largest BJ’s Restaurant & Brewhouse.<br><br>Guests can unwind at rooftop pools, indulge in spa treatments, and experience legendary hospitality — all steps away from the world’s largest BJ’s Restaurant & Brewhouse, where craft beer and California-inspired dishes keep the energy high from lunch through late night.<br><br><h2>World's Largest BJs</h2><br>Spanning multiple stories with panoramic views of West Ave and the E-District, this flagship location takes everything guests love about BJ’s and scales it to Desert City proportions. This location also features one of our largest breweries for barrel-to-tap tastiness.<br><br><h2>Gambling on Another Level</h2><br>Explore an expansive Casino featuring a multitude of gaming options as well as exclusive gamer's lounges for high-betters and willing winners.", slideshowLinks:["https://i.imgur.com/P948Ybw.png","https://i.imgur.com/4yObJfi.png","https://i.imgur.com/qvAlxgs.png","https://i.imgur.com/HNscxC4.png","https://i.imgur.com/Satd6kY.png","https://i.imgur.com/OvULKck.png","https://i.imgur.com/MIxW4Xh.png"]};
